apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    provider: elasticsearch
spec:
  ports:
  - name: client
    port: 9200
  - name: peer
    port: 9300
  selector:
    provider: elasticsearch
