apiVersion: v1
kind: ReplicationController
metadata:
  name: memcached
spec:
  replicas: 1
  selector:
    name: memcached
    provider: memcached
  template:
    metadata:
      labels:
        name: memcached
        provider: memcached
    spec:
      containers:
      - name: memcached
        image: "memcached:1.4.27"
        ports:
        - containerPort: 11211
