apiVersion: v1
kind: ReplicationController
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    name: redis
    mode: standalone
    provider: redis
  template:
    metadata:
      labels:
        name: redis
        mode: standalone
        provider: redis
        app: redis
    spec:
      containers:
      - name: redis
        image: kubernetes/redis:v1
        env:
        - name: MASTER
          value: "true"
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: /redis-master-data
          name: data
      volumes:
        - name: data
          emptyDir: {}
